### ISSUE TITLE
IndexNotReadyException in SmaliPositionManager.locationsOfLine

### ISSUE THREAD

**Issue by SmalideaIssueReporter** [SmalideaIssueReporter/smalidea-issues#105]
protocol.version: 1
os.name: Windows XP
java.version: 1.8.0_51
java.vm.vendor: Oracle Corporation
app.name: IDEA
app.name.full: IntelliJ IDEA
app.name.version: IntelliJ IDEA
app.eap: false
app.internal: false
app.build: IU-143.1184
app.version.major: 15
app.version.minor: 0.2
app.build.date: 1449417600000
app.build.date.release: 1385913600000
app.compilation.timestamp: null
update.channel.status: release
update.ignored.builds: 
plugin.name: Smalidea
plugin.version: 0.03
last.action: Stop
previous.exception: null
assignee.id: null

```
com.intellij.openapi.project.IndexNotReadyException: Please change caller according to com.intellij.openapi.project.IndexNotReadyException documentation
    at com.intellij.util.indexing.FileBasedIndexImpl.a(FileBasedIndexImpl.java:871)
    at com.intellij.util.indexing.FileBasedIndexImpl.ensureUpToDate(FileBasedIndexImpl.java:818)
    at com.intellij.util.indexing.FileBasedIndexImpl.ensureUpToDate(FileBasedIndexImpl.java:801)
    at com.intellij.psi.stubs.StubIndexImpl.a(StubIndexImpl.java:242)
    at com.intellij.psi.stubs.StubIndexImpl.processElements(StubIndexImpl.java:223)
    at com.intellij.psi.stubs.StubIndexImpl.processElements(StubIndexImpl.java:212)
    at com.intellij.psi.stubs.StubIndex.process(StubIndex.java:77)
    at com.intellij.psi.stubs.StubIndex.process(StubIndex.java:96)
    at com.intellij.psi.stubs.StubIndexImpl.get(StubIndexImpl.java:201)
    at com.intellij.psi.stubs.StubIndexImpl.get(StubIndexImpl.java:191)
    at com.intellij.psi.stubs.AbstractStubIndex.get(AbstractStubIndex.java:39)
    at org.jf.smalidea.debugging.SmaliPositionManager$2.run(SmaliPositionManager.java:129)
    at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:943)
    at org.jf.smalidea.debugging.SmaliPositionManager.locationsOfLine(SmaliPositionManager.java:125)
    at com.intellij.debugger.engine.CompoundPositionManager$3.process(CompoundPositionManager.java:128)
    at com.intellij.debugger.engine.CompoundPositionManager$3.process(CompoundPositionManager.java:125)
    at com.intellij.debugger.engine.CompoundPositionManager.a(CompoundPositionManager.java:70)
    at com.intellij.debugger.engine.CompoundPositionManager.locationsOfLine(CompoundPositionManager.java:125)
    at com.intellij.debugger.ui.breakpoints.LineBreakpoint.createRequestForPreparedClass(LineBreakpoint.java:141)
    at com.intellij.debugger.ui.breakpoints.BreakpointWithHighlighter.processClassPrepare(BreakpointWithHighlighter.java:296)
    at org.jf.smalidea.debugging.SmaliPositionManager$4.processClassPrepare(SmaliPositionManager.java:166)
    at com.intellij.debugger.engine.requests.RequestManagerImpl.processClassPrepared(RequestManagerImpl.java:420)
    at com.intellij.debugger.engine.DebugProcessEvents.a(DebugProcessEvents.java:397)
    at com.intellij.debugger.engine.DebugProcessEvents.access$300(DebugProcessEvents.java:63)
    at com.intellij.debugger.engine.DebugProcessEvents$DebuggerEventThread$3.action(DebugProcessEvents.java:246)
    at com.intellij.debugger.engine.events.DebuggerCommandImpl.run(DebuggerCommandImpl.java:45)
    at com.intellij.debugger.engine.DebuggerManagerThreadImpl.processEvent(DebuggerManagerThreadImpl.java:153)
    at com.intellij.debugger.engine.DebuggerManagerThreadImpl.processEvent(DebuggerManagerThreadImpl.java:40)
    at com.intellij.debugger.impl.InvokeThread.a(InvokeThread.java:153)
    at com.intellij.debugger.impl.InvokeThread.access$100(InvokeThread.java:31)
    at com.intellij.debugger.impl.InvokeThread$WorkerThreadRequest.run(InvokeThread.java:60)
    at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:365)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
    at org.jetbrains.ide.PooledThreadExecutor$1$1.run(PooledThreadExecutor.java:55)

-----------
Indexing started at:
java.lang.Throwable
    at com.intellij.openapi.project.DumbServiceImpl.a(DumbServiceImpl.java:160)
    at com.intellij.openapi.project.DumbServiceImpl.queueTask(DumbServiceImpl.java:85)
    at com.intellij.openapi.roots.impl.ProjectRootManagerComponent.doSynchronizeRoots(ProjectRootManagerComponent.java:298)
    at com.intellij.openapi.roots.impl.ProjectRootManagerComponent$AppListener.writeActionFinished(ProjectRootManagerComponent.java:330)
    at sun.reflect.GeneratedMethodAccessor26.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.intellij.util.EventDispatcher.dispatch(EventDispatcher.java:88)
    at com.intellij.util.EventDispatcher.access$100(EventDispatcher.java:34)
    at com.intellij.util.EventDispatcher$1.invoke(EventDispatcher.java:68)
    at com.sun.proxy.$Proxy5.writeActionFinished(Unknown Source)
    at com.intellij.openapi.application.impl.ApplicationImpl.b(ApplicationImpl.java:1416)
    at com.intellij.openapi.application.impl.ApplicationImpl.e(ApplicationImpl.java:1262)
    at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1005)
    at com.intellij.openapi.vfs.newvfs.RefreshSessionImpl$1.run(RefreshSessionImpl.java:193)
    at com.intellij.openapi.vfs.newvfs.RefreshSessionImpl.fireEvents(RefreshSessionImpl.java:206)
    at com.intellij.openapi.vfs.newvfs.RefreshQueueImpl$1$1.run(RefreshQueueImpl.java:91)
    at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:337)
    at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:321)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
    at com.intellij.ide.IdeEventQueue.f(IdeEventQueue.java:866)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:654)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:381)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

```

```
Please change caller according to com.intellij.openapi.project.IndexNotReadyException documentation
```

**Comment by JesusFreke** [comment]
I don't understand this one. Is it possible to start debugging before the project has been indexed?
