### ISSUE TITLE
java.lang.ClassCastException: com.sun.tools.jdi.ObjectReferenceImpl cannot be cast to com.sun.jdi.StringReference

### ISSUE THREAD

**Issue by SmalideaIssueReporter** [SmalideaIssueReporter/smalidea-issues#11]
protocol.version: 1
os.name: Windows 10
java.version: 1.8.0_74
java.vm.vendor: Oracle Corporation
app.name: IDEA
app.name.full: IntelliJ IDEA
app.name.version: IntelliJ IDEA
app.eap: false
app.internal: false
app.build: IU-145.1617
app.version.major: 2016
app.version.minor: 1.3
app.build.date: 1464883200000
app.build.date.release: 1458057600000
app.compilation.timestamp: null
update.channel.status: release
update.ignored.builds: 
plugin.name: Smalidea
plugin.version: 0.03
last.action: null
previous.exception: null
assignee.id: null

```
java.lang.ClassCastException: com.sun.tools.jdi.ObjectReferenceImpl cannot be cast to com.sun.jdi.StringReference
    at org.jf.smalidea.debugging.value.LazyStringReference.value(LazyStringReference.java:44)
    at com.intellij.debugger.ui.tree.render.ClassRenderer.calcLabel(ClassRenderer.java:126)
    at com.intellij.debugger.ui.tree.render.ClassRenderer.calcLabel(ClassRenderer.java:118)
    at com.intellij.debugger.ui.impl.watch.ValueDescriptorImpl.calcRepresentation(ValueDescriptorImpl.java:311)
    at com.intellij.debugger.ui.impl.watch.NodeDescriptorImpl.updateRepresentationNoNotify(NodeDescriptorImpl.java:84)
    at com.intellij.debugger.ui.impl.watch.NodeDescriptorImpl.updateRepresentation(NodeDescriptorImpl.java:76)
    at com.intellij.debugger.engine.JavaValue$1.contextAction(JavaValue.java:149)
    at com.intellij.debugger.engine.events.SuspendContextCommandImpl.action(SuspendContextCommandImpl.java:61)
    at com.intellij.debugger.engine.events.DebuggerCommandImpl.run(DebuggerCommandImpl.java:45)
    at com.intellij.debugger.engine.DebuggerManagerThreadImpl.processEvent(DebuggerManagerThreadImpl.java:153)
    at com.intellij.debugger.engine.DebuggerManagerThreadImpl.processEvent(DebuggerManagerThreadImpl.java:40)
    at com.intellij.debugger.impl.InvokeThread.a(InvokeThread.java:153)
    at com.intellij.debugger.impl.InvokeThread.access$100(InvokeThread.java:31)
    at com.intellij.debugger.impl.InvokeThread$WorkerThreadRequest.run(InvokeThread.java:60)
    at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:369)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)

```

```
com.sun.tools.jdi.ObjectReferenceImpl cannot be cast to com.sun.jdi.StringReference
```

**Comment by JesusFreke** [comment]
Added additional debugging info in https://github.com/JesusFreke/smali/commit/7a95aa296fcbe2fdde16f4e1f205f44bdc8ee499
