### ISSUE TITLE
java.lang.IllegalArgumentException: Argument for @NotNull parameter 'project' of com/intellij/psi/stubs/AbstractStubIndex.get must not be null

### ISSUE THREAD

**Issue by SmalideaIssueReporter** [SmalideaIssueReporter/smalidea-issues#137]
protocol.version: 1
os.name: Mac OS X
java.version: 1.8.0_112-release
java.vm.vendor: JetBrains s.r.o
app.name: IDEA
app.name.full: IntelliJ IDEA
app.name.version: IntelliJ IDEA
app.eap: false
app.internal: false
app.build: IU-163.9166.29
app.version.major: 2016
app.version.minor: 3.1
app.build.date: 1481287185736
app.build.date.release: 1479772845736
app.compilation.timestamp: null
update.channel.status: release
update.ignored.builds: 143.2370,162.1812.17
plugin.name: Smalidea
plugin.version: 0.03
last.action: GotoDeclaration
previous.exception: null
assignee.id: null

```
java.lang.IllegalArgumentException: Argument for @NotNull parameter 'project' of com/intellij/psi/stubs/AbstractStubIndex.get must not be null
	at com.intellij.psi.stubs.AbstractStubIndex.get(AbstractStubIndex.java)
	at org.jf.smalidea.psi.index.SmaliClassFinder.findClass(SmaliClassFinder.java:45)
	at com.intellij.psi.impl.JavaPsiFacadeImpl.b(JavaPsiFacadeImpl.java:122)
	at com.intellij.psi.impl.JavaPsiFacadeImpl.findClass(JavaPsiFacadeImpl.java:99)
	at com.intellij.codeInsight.MetaAnnotationUtil.getAnnotationTypesWithChildren(MetaAnnotationUtil.java:112)
	at com.intellij.codeInsight.MetaAnnotationUtil.lambda$null$0(MetaAnnotationUtil.java:61)
	at com.intellij.util.containers.ConcurrentFactoryMap$1.create(ConcurrentFactoryMap.java:40)
	at com.intellij.util.containers.FactoryMap.get(FactoryMap.java:57)
	at com.intellij.codeInsight.MetaAnnotationUtil.getAnnotationTypesWithChildren(MetaAnnotationUtil.java:66)
	at com.intellij.spring.model.jam.utils.JamAnnotationTypeUtilImpl.getAnnotationTypes(JamAnnotationTypeUtilImpl.java:137)
	at com.intellij.spring.model.jam.utils.JamAnnotationTypeUtilImpl.getAnnotationTypesWithChildren(JamAnnotationTypeUtilImpl.java:126)
	at com.intellij.spring.model.jam.stereotype.SpringMetaStereotypeComponent.getAnnotations(SpringMetaStereotypeComponent.java:65)
	at com.intellij.spring.model.jam.stereotype.SpringConfiguration.lambda$static$0(SpringConfiguration.java:53)
	at com.intellij.spring.model.jam.SpringJamModelImpl.getConfigurations(SpringJamModelImpl.java:139)
	at com.intellij.spring.facet.searchers.CodeConfigSearcher.search(CodeConfigSearcher.java:41)
	at com.intellij.xml.config.ConfigFileSearcher.search(ConfigFileSearcher.java:34)
	at com.intellij.spring.facet.validation.SpringUnmappedConfigurationFilesCollector.collectNotConfigured(SpringUnmappedConfigurationFilesCollector.java:169)
	at com.intellij.spring.facet.validation.SpringUnmappedConfigurationFilesCollector.collect(SpringUnmappedConfigurationFilesCollector.java:127)
	at com.intellij.spring.facet.validation.SpringConfigurationCheckTask.runCollectors(SpringConfigurationCheckTask.java:145)
	at com.intellij.spring.facet.validation.SpringConfigurationCheckTask.lambda$null$1(SpringConfigurationCheckTask.java:87)
	at com.intellij.openapi.project.DumbService$2.compute(DumbService.java:136)
	at com.intellij.openapi.project.DumbService$2.compute(DumbService.java:130)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:899)
	at com.intellij.openapi.project.DumbService.runReadActionInSmartMode(DumbService.java:130)
	at com.intellij.spring.facet.validation.SpringConfigurationCheckTask.lambda$run$2(SpringConfigurationCheckTask.java:87)
	at com.intellij.openapi.progress.impl.CoreProgressManager$3.run(CoreProgressManager.java:179)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:568)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:519)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:164)
	at com.intellij.spring.facet.validation.SpringConfigurationCheckTask.run(SpringConfigurationCheckTask.java:85)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:710)
	at com.intellij.openapi.progress.impl.CoreProgressManager$3.run(CoreProgressManager.java:179)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:568)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:519)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:164)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$1.run(ProgressManagerImpl.java:128)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:309)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

```

```
Argument for @NotNull parameter 'project' of com/intellij/psi/stubs/AbstractStubIndex.get must not be null
```

**Comment by JesusFreke** [comment]
Fixed by 
https://github.com/JesusFreke/smali/commit/8ed2f186011a4d62767681d05c5f1e58a251b110
