### ISSUE TITLE
com.intellij.openapi.project.IndexNotReadyException in SmaliPositionManager.getSourcePosition

### ISSUE THREAD

**Issue by SmalideaIssueReporter** [SmalideaIssueReporter/smalidea-issues#173]
protocol.version: 1
os.name: Windows 7
java.version: 1.8.0_60
java.vm.vendor: Oracle Corporation
app.name: IDEA
app.name.full: IntelliJ IDEA
app.name.version: IntelliJ IDEA
app.eap: false
app.internal: false
app.build: IC-139.1803
app.version.major: 14
app.version.minor: 0.5
app.build.date: 1461859200000
app.build.date.release: 1461859200000
app.compilation.timestamp: null
update.channel.status: release
update.ignored.builds: 
plugin.name: Smalidea
plugin.version: 0.03
last.action: XDebugger.CopyValue
previous.exception: null
assignee.id: null

```
com.intellij.openapi.project.IndexNotReadyException: Please change caller according to com.intellij.openapi.project.IndexNotReadyException documentation
	at com.intellij.util.indexing.FileBasedIndexImpl.handleDumbMode(FileBasedIndexImpl.java:842)
	at com.intellij.util.indexing.FileBasedIndexImpl.ensureUpToDate(FileBasedIndexImpl.java:791)
	at com.intellij.util.indexing.FileBasedIndexImpl.ensureUpToDate(FileBasedIndexImpl.java:775)
	at com.intellij.psi.stubs.StubIndexImpl.processElements(StubIndexImpl.java:249)
	at com.intellij.psi.stubs.StubIndexImpl.processElements(StubIndexImpl.java:237)
	at com.intellij.psi.stubs.StubIndex.process(StubIndex.java:76)
	at com.intellij.psi.stubs.StubIndex.process(StubIndex.java:95)
	at com.intellij.psi.stubs.StubIndexImpl.get(StubIndexImpl.java:226)
	at com.intellij.psi.stubs.StubIndexImpl.get(StubIndexImpl.java:216)
	at com.intellij.psi.stubs.AbstractStubIndex.get(AbstractStubIndex.java:39)
	at org.jf.smalidea.debugging.SmaliPositionManager.getSourcePosition(SmaliPositionManager.java:65)
	at org.jf.smalidea.debugging.SmaliPositionManager.getSourcePosition(SmaliPositionManager.java:89)
	at com.intellij.debugger.engine.CompoundPositionManager.getSourcePosition(CompoundPositionManager.java:68)
	at com.intellij.debugger.engine.ContextUtil.getSourcePosition(ContextUtil.java:66)
	at com.intellij.debugger.impl.DebuggerContextImpl$1.run(DebuggerContextImpl.java:174)
	at com.intellij.psi.impl.PsiDocumentManagerBase$7.run(PsiDocumentManagerBase.java:425)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:908)
	at com.intellij.psi.impl.PsiDocumentManagerBase.commitAndRunReadAction(PsiDocumentManagerBase.java:420)
	at com.intellij.debugger.impl.DebuggerContextImpl.initCaches(DebuggerContextImpl.java:170)
	at com.intellij.debugger.engine.JavaStackFrame.getFrameDebuggerContext(JavaStackFrame.java:157)
	at com.intellij.debugger.engine.JavaStackFrame$1.threadAction(JavaStackFrame.java:140)
	at com.intellij.debugger.engine.events.DebuggerContextCommandImpl.contextAction(DebuggerContextCommandImpl.java:59)
	at com.intellij.debugger.engine.events.SuspendContextCommandImpl.action(SuspendContextCommandImpl.java:61)
	at com.intellij.debugger.engine.events.DebuggerCommandImpl.run(DebuggerCommandImpl.java:45)
	at com.intellij.debugger.engine.DebuggerManagerThreadImpl.processEvent(DebuggerManagerThreadImpl.java:151)
	at com.intellij.debugger.engine.DebuggerManagerThreadImpl.processEvent(DebuggerManagerThreadImpl.java:39)
	at com.intellij.debugger.impl.InvokeThread.run(InvokeThread.java:146)
	at com.intellij.debugger.impl.InvokeThread.access$100(InvokeThread.java:28)
	at com.intellij.debugger.impl.InvokeThread$WorkerThreadRequest.run(InvokeThread.java:55)
	at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:406)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at org.jetbrains.ide.PooledThreadExecutor$1$1.run(PooledThreadExecutor.java:56)

```

```
Please change caller according to com.intellij.openapi.project.IndexNotReadyException documentation
```

**Comment by JesusFreke** [comment]
This one is similar to https://github.com/JesusFreke/smalidea-issues/issues/105
