### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by mohe2015** [SmalideaIssueReporter/smalidea-issues#263]
```
null
java.lang.NullPointerException
	at org.jf.dexlib2.analysis.MethodAnalyzer.addPredecessorSuccessor(MethodAnalyzer.java:560)
	at org.jf.dexlib2.analysis.MethodAnalyzer.addPredecessorSuccessor(MethodAnalyzer.java:552)
	at org.jf.dexlib2.analysis.MethodAnalyzer.buildInstructionList(MethodAnalyzer.java:542)
	at org.jf.dexlib2.analysis.MethodAnalyzer.<init>(MethodAnalyzer.java:127)
	at org.jf.smalidea.psi.impl.SmaliMethod.getMethodAnalyzer(SmaliMethod.java:327)
	at org.jf.smalidea.psi.impl.SmaliInstruction.getAnalyzedInstructionFromMethod(SmaliInstruction.java:199)
	at org.jf.smalidea.psi.impl.SmaliInstruction.getAnalyzedInstruction(SmaliInstruction.java:222)
	at org.jf.smalidea.debugging.SmaliCodeFragmentFactory.wrapContext(SmaliCodeFragmentFactory.java:138)
	at org.jf.smalidea.debugging.SmaliCodeFragmentFactory.createPresentationCodeFragment(SmaliCodeFragmentFactory.java:94)
	at com.intellij.debugger.engine.evaluation.CodeFragmentFactoryContextWrapper.createPresentationCodeFragment(CodeFragmentFactoryContextWrapper.java:66)
	at org.jetbrains.java.debugger.JavaDebuggerEditorsProvider.createExpressionCodeFragment(JavaDebuggerEditorsProvider.java:93)
	at com.intellij.xdebugger.evaluation.XDebuggerEditorsProviderBase.createDocument(XDebuggerEditorsProviderBase.java:67)
	at com.intellij.xdebugger.evaluation.XDebuggerEditorsProviderBase.createDocument(XDebuggerEditorsProviderBase.java:59)
	at com.intellij.xdebugger.impl.ui.XDebuggerEditorBase.createDocument(XDebuggerEditorBase.java:302)
	at com.intellij.xdebugger.impl.ui.XDebuggerExpressionEditor.doSetText(XDebuggerExpressionEditor.java:107)
	at com.intellij.xdebugger.impl.ui.XDebuggerEditorBase.setExpression(XDebuggerEditorBase.java:238)
	at com.intellij.xdebugger.impl.ui.XDebuggerEditorBase.setSourcePosition(XDebuggerEditorBase.java:183)
	at com.intellij.xdebugger.impl.evaluate.XDebuggerEvaluationDialog.lambda$updateSourcePosition$1(XDebuggerEvaluationDialog.java:163)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:303)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:410)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:399)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:827)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:655)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:365)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)


java.lang.NullPointerException
	at org.jf.dexlib2.analysis.MethodAnalyzer.addPredecessorSuccessor(MethodAnalyzer.java:560)
	at org.jf.dexlib2.analysis.MethodAnalyzer.addPredecessorSuccessor(MethodAnalyzer.java:552)
	at org.jf.dexlib2.analysis.MethodAnalyzer.buildInstructionList(MethodAnalyzer.java:542)
	at org.jf.dexlib2.analysis.MethodAnalyzer.<init>(MethodAnalyzer.java:127)
	at org.jf.smalidea.psi.impl.SmaliMethod.getMethodAnalyzer(SmaliMethod.java:327)
	at org.jf.smalidea.psi.impl.SmaliInstruction.getAnalyzedInstructionFromMethod(SmaliInstruction.java:199)
	at org.jf.smalidea.psi.impl.SmaliInstruction.getAnalyzedInstruction(SmaliInstruction.java:222)
	at org.jf.smalidea.debugging.SmaliCodeFragmentFactory.wrapContext(SmaliCodeFragmentFactory.java:138)
	at org.jf.smalidea.debugging.SmaliCodeFragmentFactory.createPresentationCodeFragment(SmaliCodeFragmentFactory.java:94)
	at com.intellij.debugger.engine.evaluation.CodeFragmentFactoryContextWrapper.createPresentationCodeFragment(CodeFragmentFactoryContextWrapper.java:66)
	at org.jetbrains.java.debugger.JavaDebuggerEditorsProvider.createExpressionCodeFragment(JavaDebuggerEditorsProvider.java:93)
	at com.intellij.xdebugger.evaluation.XDebuggerEditorsProviderBase.createDocument(XDebuggerEditorsProviderBase.java:67)
	at com.intellij.xdebugger.evaluation.XDebuggerEditorsProviderBase.createDocument(XDebuggerEditorsProviderBase.java:59)
	at com.intellij.xdebugger.impl.ui.XDebuggerEditorBase.createDocument(XDebuggerEditorBase.java:302)
	at com.intellij.xdebugger.impl.ui.XDebuggerExpressionEditor.doSetText(XDebuggerExpressionEditor.java:107)
	at com.intellij.xdebugger.impl.ui.XDebuggerEditorBase.setExpression(XDebuggerEditorBase.java:238)
	at com.intellij.xdebugger.impl.ui.XDebuggerEditorBase.setSourcePosition(XDebuggerEditorBase.java:183)
	at com.intellij.xdebugger.impl.evaluate.XDebuggerEvaluationDialog.lambda$updateSourcePosition$1(XDebuggerEvaluationDialog.java:163)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:303)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:410)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:399)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:827)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:655)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:365)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)


java.lang.NullPointerException
	at org.jf.dexlib2.analysis.MethodAnalyzer.addPredecessorSuccessor(MethodAnalyzer.java:560)
	at org.jf.dexlib2.analysis.MethodAnalyzer.addPredecessorSuccessor(MethodAnalyzer.java:552)
	at org.jf.dexlib2.analysis.MethodAnalyzer.buildInstructionList(MethodAnalyzer.java:542)
	at org.jf.dexlib2.analysis.MethodAnalyzer.<init>(MethodAnalyzer.java:127)
	at org.jf.smalidea.psi.impl.SmaliMethod.getMethodAnalyzer(SmaliMethod.java:327)
	at org.jf.smalidea.psi.impl.SmaliInstruction.getAnalyzedInstructionFromMethod(SmaliInstruction.java:199)
	at org.jf.smalidea.psi.impl.SmaliInstruction.getAnalyzedInstruction(SmaliInstruction.java:222)
	at org.jf.smalidea.debugging.SmaliCodeFragmentFactory.wrapContext(SmaliCodeFragmentFactory.java:138)
	at org.jf.smalidea.debugging.SmaliCodeFragmentFactory.createPresentationCodeFragment(SmaliCodeFragmentFactory.java:94)
	at com.intellij.debugger.engine.evaluation.CodeFragmentFactoryContextWrapper.createPresentationCodeFragment(CodeFragmentFactoryContextWrapper.java:66)
	at org.jetbrains.java.debugger.JavaDebuggerEditorsProvider.createExpressionCodeFragment(JavaDebuggerEditorsProvider.java:93)
	at com.intellij.xdebugger.evaluation.XDebuggerEditorsProviderBase.createDocument(XDebuggerEditorsProviderBase.java:67)
	at com.intellij.xdebugger.evaluation.XDebuggerEditorsProviderBase.createDocument(XDebuggerEditorsProviderBase.java:59)
	at com.intellij.xdebugger.impl.ui.XDebuggerEditorBase.createDocument(XDebuggerEditorBase.java:302)
	at com.intellij.xdebugger.impl.ui.XDebuggerExpressionEditor.doSetText(XDebuggerExpressionEditor.java:107)
	at com.intellij.xdebugger.impl.ui.XDebuggerEditorBase.setExpression(XDebuggerEditorBase.java:238)
	at com.intellij.xdebugger.impl.ui.XDebuggerEditorBase.setSourcePosition(XDebuggerEditorBase.java:183)
	at com.intellij.xdebugger.impl.evaluate.XDebuggerEvaluationDialog.lambda$updateSourcePosition$1(XDebuggerEvaluationDialog.java:163)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:303)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:410)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:399)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:827)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:655)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:365)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)


java.lang.NullPointerException
	at org.jf.dexlib2.analysis.MethodAnalyzer.addPredecessorSuccessor(MethodAnalyzer.java:560)
	at org.jf.dexlib2.analysis.MethodAnalyzer.addPredecessorSuccessor(MethodAnalyzer.java:552)
	at org.jf.dexlib2.analysis.MethodAnalyzer.buildInstructionList(MethodAnalyzer.java:542)
	at org.jf.dexlib2.analysis.MethodAnalyzer.<init>(MethodAnalyzer.java:127)
	at org.jf.smalidea.psi.impl.SmaliMethod.getMethodAnalyzer(SmaliMethod.java:327)
	at org.jf.smalidea.psi.impl.SmaliInstruction.getAnalyzedInstructionFromMethod(SmaliInstruction.java:199)
	at org.jf.smalidea.psi.impl.SmaliInstruction.getAnalyzedInstruction(SmaliInstruction.java:222)
	at org.jf.smalidea.debugging.SmaliCodeFragmentFactory.wrapContext(SmaliCodeFragmentFactory.java:138)
	at org.jf.smalidea.debugging.SmaliCodeFragmentFactory.createPresentationCodeFragment(SmaliCodeFragmentFactory.java:94)
	at com.intellij.debugger.engine.evaluation.CodeFragmentFactoryContextWrapper.createPresentationCodeFragment(CodeFragmentFactoryContextWrapper.java:66)
	at org.jetbrains.java.debugger.JavaDebuggerEditorsProvider.createExpressionCodeFragment(JavaDebuggerEditorsProvider.java:93)
	at com.intellij.xdebugger.evaluation.XDebuggerEditorsProviderBase.createDocument(XDebuggerEditorsProviderBase.java:67)
	at com.intellij.xdebugger.evaluation.XDebuggerEditorsProviderBase.createDocument(XDebuggerEditorsProviderBase.java:59)
	at com.intellij.xdebugger.impl.ui.XDebuggerEditorBase.createDocument(XDebuggerEditorBase.java:302)
	at com.intellij.xdebugger.impl.ui.XDebuggerExpressionEditor.doSetText(XDebuggerExpressionEditor.java:107)
	at com.intellij.xdebugger.impl.ui.XDebuggerEditorBase.setExpression(XDebuggerEditorBase.java:238)
	at com.intellij.xdebugger.impl.ui.XDebuggerEditorBase.setSourcePosition(XDebuggerEditorBase.java:183)
	at com.intellij.xdebugger.impl.evaluate.XDebuggerEvaluationDialog.lambda$updateSourcePosition$1(XDebuggerEvaluationDialog.java:163)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:303)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:410)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:399)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:827)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:655)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:365)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)


java.lang.NullPointerException
	at org.jf.dexlib2.analysis.MethodAnalyzer.addPredecessorSuccessor(MethodAnalyzer.java:560)
	at org.jf.dexlib2.analysis.MethodAnalyzer.addPredecessorSuccessor(MethodAnalyzer.java:552)
	at org.jf.dexlib2.analysis.MethodAnalyzer.buildInstructionList(MethodAnalyzer.java:542)
	at org.jf.dexlib2.analysis.MethodAnalyzer.<init>(MethodAnalyzer.java:127)
	at org.jf.smalidea.psi.impl.SmaliMethod.getMethodAnalyzer(SmaliMethod.java:327)
	at org.jf.smalidea.psi.impl.SmaliInstruction.getAnalyzedInstructionFromMethod(SmaliInstruction.java:199)
	at org.jf.smalidea.psi.impl.SmaliInstruction.getAnalyzedInstruction(SmaliInstruction.java:222)
	at org.jf.smalidea.debugging.SmaliCodeFragmentFactory.wrapContext(SmaliCodeFragmentFactory.java:138)
	at org.jf.smalidea.debugging.SmaliCodeFragmentFactory.createPresentationCodeFragment(SmaliCodeFragmentFactory.java:94)
	at com.intellij.debugger.engine.evaluation.CodeFragmentFactoryContextWrapper.createPresentationCodeFragment(CodeFragmentFactoryContextWrapper.java:66)
	at org.jetbrains.java.debugger.JavaDebuggerEditorsProvider.createExpressionCodeFragment(JavaDebuggerEditorsProvider.java:93)
	at com.intellij.xdebugger.evaluation.XDebuggerEditorsProviderBase.createDocument(XDebuggerEditorsProviderBase.java:67)
	at com.intellij.xdebugger.evaluation.XDebuggerEditorsProviderBase.createDocument(XDebuggerEditorsProviderBase.java:59)
	at com.intellij.xdebugger.impl.ui.XDebuggerEditorBase.createDocument(XDebuggerEditorBase.java:302)
	at com.intellij.xdebugger.impl.ui.XDebuggerExpressionEditor.doSetText(XDebuggerExpressionEditor.java:107)
	at com.intellij.xdebugger.impl.ui.XDebuggerEditorBase.setExpression(XDebuggerEditorBase.java:238)
	at com.intellij.xdebugger.impl.ui.XDebuggerEditorBase.setSourcePosition(XDebuggerEditorBase.java:183)
	at com.intellij.xdebugger.impl.evaluate.XDebuggerEvaluationDialog.lambda$updateSourcePosition$1(XDebuggerEvaluationDialog.java:163)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:303)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:410)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:399)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:827)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:655)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:365)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)


java.lang.NullPointerException
	at org.jf.dexlib2.analysis.MethodAnalyzer.addPredecessorSuccessor(MethodAnalyzer.java:560)
	at org.jf.dexlib2.analysis.MethodAnalyzer.addPredecessorSuccessor(MethodAnalyzer.java:552)
	at org.jf.dexlib2.analysis.MethodAnalyzer.buildInstructionList(MethodAnalyzer.java:542)
	at org.jf.dexlib2.analysis.MethodAnalyzer.<init>(MethodAnalyzer.java:127)
	at org.jf.smalidea.psi.impl.SmaliMethod.getMethodAnalyzer(SmaliMethod.java:327)
	at org.jf.smalidea.psi.impl.SmaliInstruction.getAnalyzedInstructionFromMethod(SmaliInstruction.java:199)
	at org.jf.smalidea.psi.impl.SmaliInstruction.getAnalyzedInstruction(SmaliInstruction.java:222)
	at org.jf.smalidea.debugging.SmaliCodeFragmentFactory.wrapContext(SmaliCodeFragmentFactory.java:138)
	at org.jf.smalidea.debugging.SmaliCodeFragmentFactory.createPresentationCodeFragment(SmaliCodeFragmentFactory.java:94)
	at com.intellij.debugger.engine.evaluation.CodeFragmentFactoryContextWrapper.createPresentationCodeFragment(CodeFragmentFactoryContextWrapper.java:66)
	at org.jetbrains.java.debugger.JavaDebuggerEditorsProvider.createExpressionCodeFragment(JavaDebuggerEditorsProvider.java:93)
	at com.intellij.xdebugger.evaluation.XDebuggerEditorsProviderBase.createDocument(XDebuggerEditorsProviderBase.java:67)
	at com.intellij.xdebugger.evaluation.XDebuggerEditorsProviderBase.createDocument(XDebuggerEditorsProviderBase.java:59)
	at com.intellij.xdebugger.impl.ui.XDebuggerEditorBase.createDocument(XDebuggerEditorBase.java:302)
	at com.intellij.xdebugger.impl.ui.XDebuggerExpressionEditor.doSetText(XDebuggerExpressionEditor.java:107)
	at com.intellij.xdebugger.impl.ui.XDebuggerEditorBase.setExpression(XDebuggerEditorBase.java:238)
	at com.intellij.xdebugger.impl.ui.XDebuggerEditorBase.setSourcePosition(XDebuggerEditorBase.java:183)
	at com.intellij.xdebugger.impl.evaluate.XDebuggerEvaluationDialog.lambda$updateSourcePosition$1(XDebuggerEvaluationDialog.java:163)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:303)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:410)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:399)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:827)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:655)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:365)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)


java.lang.NullPointerException
	at org.jf.dexlib2.analysis.MethodAnalyzer.addPredecessorSuccessor(MethodAnalyzer.java:560)
	at org.jf.dexlib2.analysis.MethodAnalyzer.addPredecessorSuccessor(MethodAnalyzer.java:552)
	at org.jf.dexlib2.analysis.MethodAnalyzer.buildInstructionList(MethodAnalyzer.java:542)
	at org.jf.dexlib2.analysis.MethodAnalyzer.<init>(MethodAnalyzer.java:127)
	at org.jf.smalidea.psi.impl.SmaliMethod.getMethodAnalyzer(SmaliMethod.java:327)
	at org.jf.smalidea.psi.impl.SmaliInstruction.getAnalyzedInstructionFromMethod(SmaliInstruction.java:199)
	at org.jf.smalidea.psi.impl.SmaliInstruction.getAnalyzedInstruction(SmaliInstruction.java:222)
	at org.jf.smalidea.debugging.SmaliCodeFragmentFactory.wrapContext(SmaliCodeFragmentFactory.java:138)
	at org.jf.smalidea.debugging.SmaliCodeFragmentFactory.createPresentationCodeFragment(SmaliCodeFragmentFactory.java:94)
	at com.intellij.debugger.engine.evaluation.CodeFragmentFactoryContextWrapper.createPresentationCodeFragment(CodeFragmentFactoryContextWrapper.java:66)
	at org.jetbrains.java.debugger.JavaDebuggerEditorsProvider.createExpressionCodeFragment(JavaDebuggerEditorsProvider.java:93)
	at com.intellij.xdebugger.evaluation.XDebuggerEditorsProviderBase.createDocument(XDebuggerEditorsProviderBase.java:67)
	at com.intellij.xdebugger.evaluation.XDebuggerEditorsProviderBase.createDocument(XDebuggerEditorsProviderBase.java:59)
	at com.intellij.xdebugger.impl.ui.XDebuggerEditorBase.createDocument(XDebuggerEditorBase.java:302)
	at com.intellij.xdebugger.impl.ui.XDebuggerExpressionEditor.doSetText(XDebuggerExpressionEditor.java:107)
	at com.intellij.xdebugger.impl.ui.XDebuggerEditorBase.setExpression(XDebuggerEditorBase.java:238)
	at com.intellij.xdebugger.impl.ui.XDebuggerEditorBase.setSourcePosition(XDebuggerEditorBase.java:183)
	at com.intellij.xdebugger.impl.evaluate.XDebuggerEvaluationDialog.lambda$updateSourcePosition$1(XDebuggerEvaluationDialog.java:163)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:303)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:410)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:399)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:827)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:655)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:365)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)


java.lang.NullPointerException
	at org.jf.dexlib2.analysis.MethodAnalyzer.addPredecessorSuccessor(MethodAnalyzer.java:560)
	at org.jf.dexlib2.analysis.MethodAnalyzer.addPredecessorSuccessor(MethodAnalyzer.java:552)
	at org.jf.dexlib2.analysis.MethodAnalyzer.buildInstructionList(MethodAnalyzer.java:542)
	at org.jf.dexlib2.analysis.MethodAnalyzer.<init>(MethodAnalyzer.java:127)
	at org.jf.smalidea.psi.impl.SmaliMethod.getMethodAnalyzer(SmaliMethod.java:327)
	at org.jf.smalidea.psi.impl.SmaliInstruction.getAnalyzedInstructionFromMethod(SmaliInstruction.java:199)
	at org.jf.smalidea.psi.impl.SmaliInstruction.getAnalyzedInstruction(SmaliInstruction.java:222)
	at org.jf.smalidea.debugging.SmaliCodeFragmentFactory.wrapContext(SmaliCodeFragmentFactory.java:138)
	at org.jf.smalidea.debugging.SmaliCodeFragmentFactory.createPresentationCodeFragment(SmaliCodeFragmentFactory.java:94)
	at com.intellij.debugger.engine.evaluation.CodeFragmentFactoryContextWrapper.createPresentationCodeFragment(CodeFragmentFactoryContextWrapper.java:66)
	at org.jetbrains.java.debugger.JavaDebuggerEditorsProvider.createExpressionCodeFragment(JavaDebuggerEditorsProvider.java:93)
	at com.intellij.xdebugger.evaluation.XDebuggerEditorsProviderBase.createDocument(XDebuggerEditorsProviderBase.java:67)
	at com.intellij.xdebugger.evaluation.XDebuggerEditorsProviderBase.createDocument(XDebuggerEditorsProviderBase.java:59)
	at com.intellij.xdebugger.impl.ui.XDebuggerEditorBase.createDocument(XDebuggerEditorBase.java:302)
	at com.intellij.xdebugger.impl.ui.XDebuggerExpressionEditor.doSetText(XDebuggerExpressionEditor.java:107)
	at com.intellij.xdebugger.impl.ui.XDebuggerEditorBase.setExpression(XDebuggerEditorBase.java:238)
	at com.intellij.xdebugger.impl.ui.XDebuggerEditorBase.setSourcePosition(XDebuggerEditorBase.java:183)
	at com.intellij.xdebugger.impl.evaluate.XDebuggerEvaluationDialog.lambda$updateSourcePosition$1(XDebuggerEvaluationDialog.java:163)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:303)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:410)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:399)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:827)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:655)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:365)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)



```

**Comment by mohe2015** [comment]
@JesusFreke It would be awesome if you could fix that, as it is pretty annoying. Or does that happen because I modify the code?
