### ISSUE TITLE
"Read access is allowed from event dispatch thread" in SmaliPositionManager

### ISSUE THREAD

**Issue by SmalideaIssueReporter** [SmalideaIssueReporter/smalidea-issues#29]
protocol.version: 1
os.name: Linux
java.version: 1.8.0_76-release
java.vm.vendor: Oracle Corporation
app.name: IDEA
app.name.full: IntelliJ IDEA
app.name.version: IntelliJ IDEA
app.eap: false
app.internal: false
app.build: IU-145.1617
app.version.major: 2016
app.version.minor: 1.3
app.build.date: 1464883200000
app.build.date.release: 1458057600000
app.compilation.timestamp: null
update.channel.status: release
update.ignored.builds: 
plugin.name: Smalidea
plugin.version: 0.03
last.action: CloseProject
previous.exception: null
assignee.id: null

```
java.lang.Throwable
    at com.intellij.openapi.diagnostic.Logger.error(Logger.java:138)
    at com.intellij.openapi.application.impl.ApplicationImpl.assertReadAccessAllowed(ApplicationImpl.java:1054)
    at com.intellij.debugger.SourcePosition$4.calcPsiElement(SourcePosition.java:340)
    at com.intellij.debugger.SourcePosition$SourcePositionCache.getElementAt(SourcePosition.java:164)
    at org.jf.smalidea.debugging.SmaliPositionManager.locationsOfLine(SmaliPositionManager.java:119)
    at com.intellij.debugger.engine.CompoundPositionManager.a(CompoundPositionManager.java:124)
    at com.intellij.debugger.engine.CompoundPositionManager.a(CompoundPositionManager.java:69)
    at com.intellij.debugger.engine.CompoundPositionManager.locationsOfLine(CompoundPositionManager.java:124)
    at org.jetbrains.plugins.scala.debugger.ScalaPositionManager$MyClassPrepareRequestor.processClassPrepare(ScalaPositionManager.scala:857)
    at com.intellij.debugger.engine.requests.RequestManagerImpl.processClassPrepared(RequestManagerImpl.java:420)
    at com.intellij.debugger.engine.DebugProcessEvents.a(DebugProcessEvents.java:381)
    at com.intellij.debugger.engine.DebugProcessEvents.access$300(DebugProcessEvents.java:58)
    at com.intellij.debugger.engine.DebugProcessEvents$DebuggerEventThread$1.action(DebugProcessEvents.java:230)
    at com.intellij.debugger.engine.events.DebuggerCommandImpl.run(DebuggerCommandImpl.java:45)
    at com.intellij.debugger.engine.DebuggerManagerThreadImpl.processEvent(DebuggerManagerThreadImpl.java:153)
    at com.intellij.debugger.engine.DebuggerManagerThreadImpl.processEvent(DebuggerManagerThreadImpl.java:40)
    at com.intellij.debugger.impl.InvokeThread.a(InvokeThread.java:153)
    at com.intellij.debugger.impl.InvokeThread.access$100(InvokeThread.java:31)
    at com.intellij.debugger.impl.InvokeThread$WorkerThreadRequest.run(InvokeThread.java:60)
    at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:369)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)

```

```
Read access is allowed from event dispatch thread or inside read-action only (see com.intellij.openapi.application.Application.runReadAction())
Details: Current thread: Thread[ApplicationImpl pooled thread 344,4,main] 2006235914
; dispatch thread: false; isDispatchThread(): false
SystemEventQueueThread: Thread[AWT-EventQueue-0 2016.1.3#IU-145.1617.8 IDEA, eap:false, os:Linux 4.4.0-21-generic, java-version:JetBrains s.r.o 1.8.0_76-release-b198,6,main] 420722883
```

**Comment by JesusFreke** [comment]
Related (but not duplicate) issue: #56

**Comment by JesusFreke** [comment]
Fixed by https://github.com/JesusFreke/smali/commit/a15fc84ace690365ad55b66c98b27ffa7c35f1e6
