### ISSUE TITLE
PSI elements displayed in choose by name lists must return a non-null value from getPresentation()

### ISSUE THREAD

**Issue by JesusFreke** [SmalideaIssueReporter/smalidea-issues#3]
(this was using .03, with idea ultimate 14.1.1)

PSI elements displayed in choose by name lists must return a non-null value from getPresentation(): element SmaliClass(CLASS), class org.jf.smalidea.psi.impl.SmaliClass
java.lang.AssertionError: PSI elements displayed in choose by name lists must return a non-null value from getPresentation(): element SmaliClass(CLASS), class org.jf.smalidea.psi.impl.SmaliClass
    at com.intellij.ide.util.NavigationItemListCellRenderer$LeftRenderer.customizeCellRenderer(NavigationItemListCellRenderer.java:147)
    at com.intellij.ui.ColoredListCellRenderer.getListCellRendererComponent(ColoredListCellRenderer.java:75)
    at com.intellij.ide.util.NavigationItemListCellRenderer.getListCellRendererComponent(NavigationItemListCellRenderer.java:75)
    at com.intellij.ide.util.gotoByName.ContributorsBasedGotoByModel$1.getListCellRendererComponent(ContributorsBasedGotoByModel.java:78)
    at com.intellij.ui.ExpandedItemListCellRendererWrapper.getListCellRendererComponent(ExpandedItemListCellRendererWrapper.java:34)
    at javax.swing.plaf.basic.BasicListUI.updateLayoutState(BasicListUI.java:1361)
    at javax.swing.plaf.basic.BasicListUI.maybeUpdateLayoutState(BasicListUI.java:1311)
    at javax.swing.plaf.basic.BasicListUI.getPreferredSize(BasicListUI.java:578)
    at javax.swing.JComponent.getPreferredSize(JComponent.java:1660)
    at com.intellij.ui.components.JBList.getPreferredSize(JBList.java:161)
    at javax.swing.JList.getPreferredScrollableViewportSize(JList.java:2449)
    at javax.swing.ViewportLayout.preferredLayoutSize(ViewportLayout.java:92)
    at java.awt.Container.preferredSize(Container.java:1788)
    at java.awt.Container.getPreferredSize(Container.java:1773)
    at javax.swing.JComponent.getPreferredSize(JComponent.java:1662)
    at javax.swing.ScrollPaneLayout.preferredLayoutSize(ScrollPaneLayout.java:492)
    at java.awt.Container.preferredSize(Container.java:1788)
    at java.awt.Container.getPreferredSize(Container.java:1773)
    at javax.swing.JComponent.getPreferredSize(JComponent.java:1662)
    at com.intellij.ide.util.gotoByName.ChooseByNamePopup.showList(ChooseByNamePopup.java:144)
    at com.intellij.ide.util.gotoByName.ChooseByNameBase$ListUpdater$1.run(ChooseByNameBase.java:1160)
    at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:238)
    at com.intellij.util.Alarm$Request$1.run(Alarm.java:351)
    at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:332)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:312)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:733)
    at java.awt.EventQueue.access$200(EventQueue.java:103)
    at java.awt.EventQueue$3.run(EventQueue.java:694)
    at java.awt.EventQueue$3.run(EventQueue.java:692)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:703)
    at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:734)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:569)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)

**Comment by JesusFreke** [comment]
Fixed by https://github.com/JesusFreke/smali/commit/a95d0a43a52560ecd3be975d443d4126523a2e6c
