### ISSUE TITLE
java.lang.AssertionError in LazyValue.getValue

### ISSUE THREAD

**Issue by SmalideaIssueReporter** [SmalideaIssueReporter/smalidea-issues#4]
protocol.version: 1
os.name: Windows 7
java.version: 1.8.0_60
java.vm.vendor: Oracle Corporation
app.name: IDEA
app.name.full: IntelliJ IDEA
app.name.version: IntelliJ IDEA
app.eap: false
app.internal: false
app.build: IC-145.258
app.version.major: 2016
app.version.minor: 1
app.build.date: 1458144000000
app.build.date.release: 1458144000000
app.compilation.timestamp: null
update.channel.status: release
update.ignored.builds: 
plugin.name: Smalidea
plugin.version: 0.03
last.action: StepOver
previous.exception: null
assignee.id: null

```
java.lang.AssertionError
    at org.jf.smalidea.debugging.value.LazyValue.getValue(LazyValue.java:128)
    at org.jf.smalidea.debugging.value.LazyObjectReference.disableCollection(LazyObjectReference.java:48)
    at com.intellij.debugger.impl.DebuggerUtilsEx.disableCollection(DebuggerUtilsEx.java:945)
    at com.intellij.debugger.engine.SuspendContextImpl.keep(SuspendContextImpl.java:205)
    at com.intellij.debugger.impl.DebuggerUtilsEx.keep(DebuggerUtilsEx.java:455)
    at com.intellij.debugger.ui.impl.watch.EvaluationDescriptor.calcValue(EvaluationDescriptor.java:127)
    at com.intellij.debugger.ui.impl.watch.ValueDescriptorImpl.setContext(ValueDescriptorImpl.java:199)
    at com.intellij.debugger.engine.JavaDebuggerEvaluator$1.threadAction(JavaDebuggerEvaluator.java:95)
    at com.intellij.debugger.engine.events.DebuggerContextCommandImpl.contextAction(DebuggerContextCommandImpl.java:83)
    at com.intellij.debugger.engine.events.SuspendContextCommandImpl.action(SuspendContextCommandImpl.java:61)
    at com.intellij.debugger.engine.events.DebuggerCommandImpl.run(DebuggerCommandImpl.java:45)
    at com.intellij.debugger.engine.DebuggerManagerThreadImpl.processEvent(DebuggerManagerThreadImpl.java:153)
    at com.intellij.debugger.engine.DebuggerManagerThreadImpl.processEvent(DebuggerManagerThreadImpl.java:40)
    at com.intellij.debugger.impl.InvokeThread.run(InvokeThread.java:153)
    at com.intellij.debugger.impl.InvokeThread.access$100(InvokeThread.java:31)
    at com.intellij.debugger.impl.InvokeThread$WorkerThreadRequest.run(InvokeThread.java:60)
    at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:369)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)

```

```
null
```

**Comment by JesusFreke** [comment]
Added additional info to help troubleshoot this in https://github.com/JesusFreke/smali/commit/3aad871652025f8410051561f8e31e6b6ca140cc
