### ISSUE TITLE
org.jf.dexlib2.analysis.UnresolvedClassException: Could not resolve class ...

### ISSUE THREAD

**Issue by SmalideaIssueReporter** [SmalideaIssueReporter/smalidea-issues#5]
protocol.version: 1
os.name: Windows 7
java.version: 1.8.0_60
java.vm.vendor: Oracle Corporation
app.name: IDEA
app.name.full: IntelliJ IDEA
app.name.version: IntelliJ IDEA
app.eap: false
app.internal: false
app.build: IU-145.597
app.version.major: 2016
app.version.minor: 1.1
app.build.date: 1459180800000
app.build.date.release: 1458057600000
app.compilation.timestamp: null
update.channel.status: release
update.ignored.builds: 
plugin.name: Smalidea
plugin.version: 0.03
last.action: StepOver
previous.exception: null
assignee.id: null

```
org.jf.dexlib2.analysis.UnresolvedClassException: Could not resolve class Landroid/view/ContextThemeWrapper;
    at org.jf.dexlib2.analysis.ClassPath.getClassDef(ClassPath.java:155)
    at org.jf.dexlib2.analysis.ClassProto$1.get(ClassProto.java:94)
    at org.jf.dexlib2.analysis.ClassProto$1.get(ClassProto.java:92)
    at com.google.common.base.Suppliers$MemoizingSupplier.get(Suppliers.java:125)
    at org.jf.dexlib2.analysis.ClassProto.getClassDef(ClassProto.java:88)
    at org.jf.dexlib2.analysis.ClassProto.isInterface(ClassProto.java:106)
    at org.jf.dexlib2.analysis.MethodAnalyzer.analyzeInstanceOf(MethodAnalyzer.java:1184)
    at org.jf.dexlib2.analysis.MethodAnalyzer.analyzeInstruction(MethodAnalyzer.java:649)
    at org.jf.dexlib2.analysis.MethodAnalyzer.analyze(MethodAnalyzer.java:206)
    at org.jf.dexlib2.analysis.MethodAnalyzer.<init>(MethodAnalyzer.java:141)
    at org.jf.smalidea.psi.impl.SmaliMethod.getMethodAnalyzer(SmaliMethod.java:327)
    at org.jf.smalidea.psi.impl.SmaliInstruction.getAnalyzedInstructionFromMethod(SmaliInstruction.java:199)
    at org.jf.smalidea.psi.impl.SmaliInstruction.getAnalyzedInstruction(SmaliInstruction.java:222)
    at org.jf.smalidea.debugging.SmaliCodeFragmentFactory.wrapContext(SmaliCodeFragmentFactory.java:137)
    at org.jf.smalidea.debugging.SmaliCodeFragmentFactory.createCodeFragment(SmaliCodeFragmentFactory.java:74)
    at com.intellij.debugger.engine.evaluation.CodeFragmentFactoryContextWrapper.createCodeFragment(CodeFragmentFactoryContextWrapper.java:57)
    at com.intellij.debugger.ui.impl.watch.EvaluationDescriptor.createCodeFragment(EvaluationDescriptor.java:70)
    at com.intellij.debugger.ui.impl.watch.WatchItemDescriptor.getEvaluationCode(WatchItemDescriptor.java:86)
    at com.intellij.debugger.ui.impl.watch.EvaluationDescriptor$1.compute(EvaluationDescriptor.java:85)
    at com.intellij.debugger.ui.impl.watch.EvaluationDescriptor$1.compute(EvaluationDescriptor.java:81)
    at com.intellij.debugger.DebuggerInvocationUtil$3.compute(DebuggerInvocationUtil.java:76)
    at com.intellij.psi.impl.PsiDocumentManagerBase$6.run(PsiDocumentManagerBase.java:414)
    at com.intellij.psi.impl.PsiDocumentManagerBase$7.run(PsiDocumentManagerBase.java:446)
    at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:950)
    at com.intellij.psi.impl.PsiDocumentManagerBase.commitAndRunReadAction(PsiDocumentManagerBase.java:441)
    at com.intellij.psi.impl.PsiDocumentManagerBase.commitAndRunReadAction(PsiDocumentManagerBase.java:411)
    at com.intellij.debugger.DebuggerInvocationUtil.commitAndRunReadAction(DebuggerInvocationUtil.java:72)
    at com.intellij.debugger.ui.impl.watch.EvaluationDescriptor.calcValue(EvaluationDescriptor.java:81)
    at com.intellij.debugger.ui.impl.watch.ValueDescriptorImpl.setContext(ValueDescriptorImpl.java:199)
    at com.intellij.debugger.engine.JavaDebuggerEvaluator$1.threadAction(JavaDebuggerEvaluator.java:95)
    at com.intellij.debugger.engine.events.DebuggerContextCommandImpl.contextAction(DebuggerContextCommandImpl.java:83)
    at com.intellij.debugger.engine.events.SuspendContextCommandImpl.action(SuspendContextCommandImpl.java:61)
    at com.intellij.debugger.engine.events.DebuggerCommandImpl.run(DebuggerCommandImpl.java:45)
    at com.intellij.debugger.engine.DebuggerManagerThreadImpl.processEvent(DebuggerManagerThreadImpl.java:153)
    at com.intellij.debugger.engine.DebuggerManagerThreadImpl.processEvent(DebuggerManagerThreadImpl.java:40)
    at com.intellij.debugger.impl.InvokeThread.a(InvokeThread.java:153)
    at com.intellij.debugger.impl.InvokeThread.access$100(InvokeThread.java:31)
    at com.intellij.debugger.impl.InvokeThread$WorkerThreadRequest.run(InvokeThread.java:60)
    at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:369)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)


```

```
Could not resolve class Landroid/view/ContextThemeWrapper;
```

**Comment by JesusFreke** [comment]
I think this particular crash is no longer relevant after https://github.com/JesusFreke/smali/commit/93100e57b271cb408ec4d4247493f1336425662a, although it's worth thinking about how to handle this type of problem in the general case
