### ISSUE TITLE
java.lang.NoSuchMethodError: SmaliMethod.getStubOrPsiParent

### ISSUE THREAD

**Issue by SmalideaIssueReporter** [SmalideaIssueReporter/smalidea-issues#54]
protocol.version: 1
os.name: Mac OS X
java.version: 1.8.0_76-release
java.vm.vendor: Oracle Corporation
app.name: IDEA
app.name.full: IntelliJ IDEA
app.name.version: IntelliJ IDEA
app.eap: false
app.internal: false
app.build: IC-162.1628.40
app.version.major: 2016
app.version.minor: 2.2
app.build.date: 1471320000000
app.build.date.release: 1471320000000
app.compilation.timestamp: null
update.channel.status: release
update.ignored.builds: 
plugin.name: Smalidea
plugin.version: 0.03
last.action: Debug
previous.exception: null
assignee.id: null

```
java.lang.NoSuchMethodError: org.jf.smalidea.psi.impl.SmaliMethod.getStubOrPsiParent()Lcom/intellij/psi/PsiElement;
    at org.jf.smalidea.psi.impl.SmaliMethod.getContainingClass(SmaliMethod.java:262)
    at org.jf.smalidea.psi.impl.SmaliMethod.getContainingClass(SmaliMethod.java:66)
    at com.intellij.debugger.engine.JVMNameUtil.getJVMSignature(JVMNameUtil.java:327)
    at com.intellij.debugger.ui.breakpoints.MethodBreakpoint$1.compute(MethodBreakpoint.java:329)
    at com.intellij.debugger.ui.breakpoints.MethodBreakpoint$1.compute(MethodBreakpoint.java:307)
    at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:867)
    at com.intellij.debugger.ui.breakpoints.MethodBreakpoint.getMethodDescriptor(MethodBreakpoint.java:307)
    at com.intellij.debugger.ui.breakpoints.MethodBreakpoint.reload(MethodBreakpoint.java:111)
    at com.intellij.debugger.ui.breakpoints.BreakpointWithHighlighter.reload(BreakpointWithHighlighter.java:242)
    at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:851)
    at com.intellij.debugger.ui.breakpoints.BreakpointWithHighlighter.<init>(BreakpointWithHighlighter.java:178)
    at com.intellij.debugger.ui.breakpoints.MethodBreakpoint.<init>(MethodBreakpoint.java:76)
    at com.intellij.debugger.ui.breakpoints.JavaMethodBreakpointType.createJavaBreakpoint(JavaMethodBreakpointType.java:129)
    at com.intellij.debugger.ui.breakpoints.BreakpointManager.getJavaBreakpoint(BreakpointManager.java:513)
    at com.intellij.debugger.ui.breakpoints.BreakpointManager$3.fun(BreakpointManager.java:500)
    at com.intellij.debugger.ui.breakpoints.BreakpointManager$3.fun(BreakpointManager.java:497)
    at com.intellij.util.containers.ContainerUtil.mapNotNull(ContainerUtil.java:1888)
    at com.intellij.util.containers.ContainerUtil.mapNotNull(ContainerUtil.java:1837)
    at com.intellij.debugger.ui.breakpoints.BreakpointManager.lambda$getBreakpoints$7(BreakpointManager.java:497)
    at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:867)
    at com.intellij.debugger.ui.breakpoints.BreakpointManager.getBreakpoints(BreakpointManager.java:497)
    at com.intellij.debugger.ui.breakpoints.BreakpointManager.reloadBreakpoints(BreakpointManager.java:620)
    at com.intellij.debugger.engine.DebugProcessImpl.createVirtualMachine(DebugProcessImpl.java:1953)
    at com.intellij.debugger.engine.DebugProcessImpl.attachVirtualMachine(DebugProcessImpl.java:1873)
    at com.intellij.debugger.impl.DebuggerSession.attach(DebuggerSession.java:429)
    at com.intellij.debugger.impl.DebuggerSession.create(DebuggerSession.java:192)
    at com.intellij.debugger.impl.DebuggerManagerImpl.attachVirtualMachine(DebuggerManagerImpl.java:224)
    at com.intellij.debugger.impl.GenericDebuggerRunner.attachVirtualMachine(GenericDebuggerRunner.java:113)
    at com.intellij.debugger.impl.GenericDebuggerRunner.attachVirtualMachine(GenericDebuggerRunner.java:103)
    at com.intellij.debugger.impl.GenericDebuggerRunner.createContentDescriptor(GenericDebuggerRunner.java:92)
    at com.intellij.debugger.impl.GenericDebuggerRunner.doExecute(GenericDebuggerRunner.java:61)
    at com.intellij.execution.runners.GenericProgramRunner$1.execute(GenericProgramRunner.java:43)
    at com.intellij.execution.impl.ExecutionManagerImpl.lambda$startRunProfile$3(ExecutionManagerImpl.java:380)
    at com.intellij.openapi.application.TransactionGuardImpl.runSyncTransaction(TransactionGuardImpl.java:88)
    at com.intellij.openapi.application.TransactionGuardImpl.access$300(TransactionGuardImpl.java:40)
    at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:113)
    at com.intellij.openapi.application.TransactionGuardImpl.submitTransaction(TransactionGuardImpl.java:123)
    at com.intellij.openapi.application.TransactionGuard.submitTransaction(TransactionGuard.java:109)
    at com.intellij.execution.impl.ExecutionManagerImpl.lambda$startRunProfile$4(ExecutionManagerImpl.java:417)
    at com.intellij.execution.impl.ExecutionManagerImpl.compileAndRun(ExecutionManagerImpl.java:292)
    at com.intellij.execution.impl.ExecutionManagerImpl.startRunProfile(ExecutionManagerImpl.java:417)
    at com.intellij.execution.runners.GenericProgramRunner.execute(GenericProgramRunner.java:40)
    at com.intellij.execution.runners.BaseProgramRunner.execute(BaseProgramRunner.java:61)
    at com.intellij.execution.runners.BaseProgramRunner.execute(BaseProgramRunner.java:50)
    at com.intellij.execution.ProgramRunnerUtil.executeConfiguration(ProgramRunnerUtil.java:118)
    at com.intellij.execution.impl.ExecutionManagerImpl.start(ExecutionManagerImpl.java:117)
    at com.intellij.execution.impl.ExecutionManagerImpl.access$300(ExecutionManagerImpl.java:67)
    at com.intellij.execution.impl.ExecutionManagerImpl$3.run(ExecutionManagerImpl.java:509)
    at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:222)
    at com.intellij.util.Alarm$Request$1.run(Alarm.java:378)
    at com.intellij.openapi.application.TransactionGuardImpl$6.run(TransactionGuardImpl.java:291)
    at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:326)
    at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:310)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
    at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:863)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:699)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:385)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

```

```
org.jf.smalidea.psi.impl.SmaliMethod.getStubOrPsiParent()Lcom/intellij/psi/PsiElement;
```

**Comment by JesusFreke** [comment]
Fixed by https://github.com/JesusFreke/smali/commit/a15fc84ace690365ad55b66c98b27ffa7c35f1e6
