### ISSUE TITLE
"Unexpected termination offset for lexer"

### ISSUE THREAD

**Issue by JesusFreke** [SmalideaIssueReporter/smalidea-issues#61]
Unexpected termination offset for lexer org.jf.smalidea.SmaliLexer@32c1a268
java.lang.IllegalStateException: Unexpected termination offset for lexer org.jf.smalidea.SmaliLexer@32c1a268
    at com.intellij.openapi.editor.ex.util.LexerEditorHighlighter.doSetText(LexerEditorHighlighter.java:350)
    at com.intellij.openapi.editor.ex.util.LexerEditorHighlighter.setText(LexerEditorHighlighter.java:316)
    at com.intellij.psi.impl.cache.impl.id.PlatformIdTableBuilding$TokenSetTodoIndexer.map(PlatformIdTableBuilding.java:165)
    at com.intellij.psi.impl.cache.impl.id.PlatformIdTableBuilding$TokenSetTodoIndexer.map(PlatformIdTableBuilding.java:142)
    at com.intellij.psi.impl.cache.impl.todo.TodoIndex$4.map(TodoIndex.java:108)
    at com.intellij.psi.impl.cache.impl.todo.TodoIndex$4.map(TodoIndex.java:100)
    at com.intellij.util.indexing.MapReduceIndex.update(MapReduceIndex.java:457)
    at com.intellij.util.indexing.FileBasedIndexImpl.updateSingleIndex(FileBasedIndexImpl.java:1633)
    at com.intellij.util.indexing.FileBasedIndexImpl.lambda$doIndexFileContent$8(FileBasedIndexImpl.java:1559)
    at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.freezeFileTypeTemporarilyIn(FileTypeManagerImpl.java:505)
    at com.intellij.util.indexing.FileBasedIndexImpl.doIndexFileContent(FileBasedIndexImpl.java:1516)
    at com.intellij.util.indexing.FileBasedIndexImpl.indexFileContent(FileBasedIndexImpl.java:1501)
    at com.intellij.util.indexing.FileBasedIndexImpl.processRefreshedFile(FileBasedIndexImpl.java:1482)
    at com.intellij.util.indexing.FileBasedIndexImpl$VirtualFileUpdateTask.doProcess(FileBasedIndexImpl.java:1650)
    at com.intellij.util.indexing.FileBasedIndexImpl$VirtualFileUpdateTask.doProcess(FileBasedIndexImpl.java:1647)
    at com.intellij.util.indexing.UpdateTask.process(UpdateTask.java:80)
    at com.intellij.util.indexing.UpdateTask.processAll(UpdateTask.java:47)
    at com.intellij.util.indexing.FileBasedIndexImpl.forceUpdate(FileBasedIndexImpl.java:1669)
    at com.intellij.util.indexing.FileBasedIndexImpl.ensureUpToDate(FileBasedIndexImpl.java:713)
    at com.intellij.util.indexing.FileBasedIndexImpl.ensureUpToDate(FileBasedIndexImpl.java:681)
    at com.intellij.psi.stubs.StubIndexImpl.processAllKeys(StubIndexImpl.java:401)
    at com.intellij.psi.stubs.StubIndexImpl.processAllKeys(StubIndexImpl.java:396)
    at com.intellij.psi.stubs.StubIndexImpl.getAllKeys(StubIndexImpl.java:390)
    at com.intellij.psi.stubs.AbstractStubIndex.getAllKeys(AbstractStubIndex.java:31)
    at org.jetbrains.kotlin.idea.stubindex.SubpackagesIndexService$cachedValue$1.compute(SubpackagesIndexService.kt:34)
    at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:49)
    at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:222)
    at com.intellij.psi.impl.PsiCachedValue.getValueWithLock(PsiCachedValue.java:65)
    at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:38)
    at org.jetbrains.kotlin.idea.stubindex.SubpackagesIndexService$Companion.getInstance(SubpackagesIndexService.kt:87)
    at org.jetbrains.kotlin.idea.stubindex.PackageIndexUtil.getSubPackageFqNames(PackageIndexUtil.kt:33)
    at org.jetbrains.kotlin.idea.caches.resolve.IDELightClassGenerationSupport.getSubPackages(IDELightClassGenerationSupport.kt:133)
    at org.jetbrains.kotlin.asJava.JavaElementFinder.getSubPackages(JavaElementFinder.java:179)
    at com.intellij.psi.impl.JavaPsiFacadeImpl.getSubPackages(JavaPsiFacadeImpl.java:351)
    at com.intellij.psi.impl.file.PsiPackageImpl.getSubPackages(PsiPackageImpl.java:188)
    at com.intellij.psi.impl.file.PsiPackageImpl.processDeclarations(PsiPackageImpl.java:342)
    at com.intellij.psi.impl.source.PsiJavaFileBaseImpl.processDeclarationsNoGuess(PsiJavaFileBaseImpl.java:346)
    at com.intellij.psi.impl.source.PsiJavaFileBaseImpl.access$200(PsiJavaFileBaseImpl.java:58)
    at com.intellij.psi.impl.source.PsiJavaFileBaseImpl$MyCacheBuilder.compute(PsiJavaFileBaseImpl.java:511)
    at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:49)
    at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:222)
    at com.intellij.psi.impl.PsiCachedValue.getValueWithLock(PsiCachedValue.java:65)
    at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:38)
    at com.intellij.psi.impl.source.PsiJavaFileBaseImpl.processDeclarations(PsiJavaFileBaseImpl.java:298)
    at com.intellij.psi.scope.util.PsiScopesUtil.treeWalkUp(PsiScopesUtil.java:68)
    at com.intellij.psi.scope.util.PsiScopesUtil.treeWalkUp(PsiScopesUtil.java:50)
    at com.intellij.psi.scope.util.PsiScopesUtil.resolveAndWalk(PsiScopesUtil.java:226)
    at com.intellij.psi.scope.util.PsiScopesUtil.resolveAndWalk(PsiScopesUtil.java:157)
    at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.resolve(PsiJavaCodeReferenceElementImpl.java:448)
    at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.access$100(PsiJavaCodeReferenceElementImpl.java:55)
    at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl$OurGenericsResolver.resolve(PsiJavaCodeReferenceElementImpl.java:350)
    at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl$OurGenericsResolver.resolve(PsiJavaCodeReferenceElementImpl.java:342)
    at com.intellij.psi.impl.source.resolve.ResolveCache$4.compute(ResolveCache.java:191)
    at com.intellij.psi.impl.source.resolve.ResolveCache$4.compute(ResolveCache.java:188)
    at com.intellij.openapi.util.RecursionManager$2.doPreventingRecursion(RecursionManager.java:112)
    at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:188)
    at com.intellij.psi.impl.PsiImplUtil.multiResolveImpl(PsiImplUtil.java:752)
    at com.intellij.psi.impl.PsiImplUtil.multiResolveImpl(PsiImplUtil.java:741)
    at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.multiResolve(PsiJavaCodeReferenceElementImpl.java:377)
    at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.advancedResolve(PsiJavaCodeReferenceElementImpl.java:370)
    at com.intellij.psi.impl.source.PsiClassReferenceType.resolveGenerics(PsiClassReferenceType.java:145)
    at com.intellij.psi.impl.TypeCorrector.correctType(TypeCorrector.java:55)
    at com.intellij.psi.impl.PsiClassImplUtil.correctType(PsiClassImplUtil.java:736)
    at com.intellij.psi.impl.ScopedClassHierarchy.visitType(ScopedClassHierarchy.java:92)
    at com.intellij.psi.impl.ScopedClassHierarchy.getSuperClassSubstitutor(ScopedClassHierarchy.java:135)
    at com.intellij.psi.impl.JavaClassSupersImpl.getSuperSubstitutorWithCaching(JavaClassSupersImpl.java:108)
    at com.intellij.psi.impl.JavaClassSupersImpl.getSuperClassSubstitutor(JavaClassSupersImpl.java:68)
    at com.intellij.psi.impl.InheritanceImplUtil.isInheritor(InheritanceImplUtil.java:41)
    at com.intellij.psi.impl.source.PsiClassImpl.isInheritor(PsiClassImpl.java:626)
    at com.intellij.psi.util.InheritanceUtil.isInheritorOrSelf(InheritanceUtil.java:41)
    at com.intellij.psi.impl.ElementPresentationUtil.getClassKindImpl(ElementPresentationUtil.java:136)
    at com.intellij.psi.impl.ElementPresentationUtil.access$000(ElementPresentationUtil.java:37)
    at com.intellij.psi.impl.ElementPresentationUtil$1.compute(ElementPresentationUtil.java:108)
    at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:49)
    at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:222)
    at com.intellij.psi.impl.PsiCachedValue.getValueWithLock(PsiCachedValue.java:65)
    at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:38)
    at com.intellij.psi.impl.ElementPresentationUtil.getClassKind(ElementPresentationUtil.java:113)
    at com.intellij.psi.impl.PsiClassImplUtil$1.fun(PsiClassImplUtil.java:261)
    at com.intellij.psi.impl.PsiClassImplUtil$1.fun(PsiClassImplUtil.java:253)
    at com.intellij.ui.IconDeferrerImpl.deferImpl(IconDeferrerImpl.java:82)
    at com.intellij.ui.IconDeferrerImpl.defer(IconDeferrerImpl.java:72)
    at com.intellij.psi.impl.PsiClassImplUtil.getClassIcon(PsiClassImplUtil.java:283)
    at com.intellij.psi.impl.PsiClassImplUtil.getClassIcon(PsiClassImplUtil.java:270)
    at com.intellij.psi.impl.source.PsiClassImpl.getElementIcon(PsiClassImpl.java:641)
    at com.intellij.psi.impl.ElementBase.computeIconNow(ElementBase.java:126)
    at com.intellij.psi.impl.ElementBase.access$000(ElementBase.java:51)
    at com.intellij.psi.impl.ElementBase$1.fun(ElementBase.java:62)
    at com.intellij.psi.impl.ElementBase$1.fun(ElementBase.java:55)
    at com.intellij.ui.IconDeferrerImpl.deferImpl(IconDeferrerImpl.java:82)
    at com.intellij.ui.IconDeferrerImpl.defer(IconDeferrerImpl.java:72)
    at com.intellij.psi.impl.ElementBase.computeIcon(ElementBase.java:114)
    at com.intellij.psi.impl.ElementBase.getIcon(ElementBase.java:90)
    at com.intellij.ide.JavaFileIconPatcher.replaceIcon(JavaFileIconPatcher.java:72)
    at com.intellij.ide.JavaFileIconPatcher.patchIcon(JavaFileIconPatcher.java:45)
    at com.intellij.util.IconUtil$2.fun(IconUtil.java:155)
    at com.intellij.util.IconUtil$2.fun(IconUtil.java:136)
    at com.intellij.ui.DeferredIconImpl.evaluate(DeferredIconImpl.java:253)
    at com.intellij.ui.DeferredIconImpl.lambda$null$0(DeferredIconImpl.java:139)
    at com.intellij.ui.IconDeferrerImpl.evaluateDeferred(IconDeferrerImpl.java:117)
    at com.intellij.ui.DeferredIconImpl.lambda$null$1(DeferredIconImpl.java:139)
    at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1034)
    at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runInReadActionWithWriteActionPriority$0(ProgressIndicatorUtils.java:80)
    at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$2(ProgressIndicatorUtils.java:135)
    at com.intellij.openapi.progress.impl.CoreProgressManager$3.run(CoreProgressManager.java:170)
    at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:494)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:443)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:155)
    at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:133)
    at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:80)
    at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:101)
    at com.intellij.ui.DeferredIconImpl.lambda$paintIcon$4(DeferredIconImpl.java:138)
    at com.intellij.util.concurrency.BoundedTaskExecutor.runFirstTaskThenPollAndRunRest(BoundedTaskExecutor.java:178)
    at com.intellij.util.concurrency.BoundedTaskExecutor.access$000(BoundedTaskExecutor.java:40)
    at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:197)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)

**Comment by JesusFreke** [comment]
Duplicate of #12
