### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException in SmaliCodeFragmentFactory.evaluateRegister

### ISSUE THREAD

**Issue by SmalideaIssueReporter** [SmalideaIssueReporter/smalidea-issues#8]
protocol.version: 1
os.name: Windows 10
java.version: 1.8.0_77
java.vm.vendor: Oracle Corporation
app.name: IDEA
app.name.full: IntelliJ IDEA
app.name.version: IntelliJ IDEA
app.eap: false
app.internal: false
app.build: IC-145.972
app.version.major: 2016
app.version.minor: 1.2
app.build.date: 1463205600000
app.build.date.release: 1463205600000
app.compilation.timestamp: null
update.channel.status: release
update.ignored.builds: 
plugin.name: Smalidea
plugin.version: 0.03
last.action: StepInto
previous.exception: null
assignee.id: null

```
java.lang.ArrayIndexOutOfBoundsException: 4
    at com.sun.tools.jdi.PacketStream.readByte(PacketStream.java:297)
    at com.sun.tools.jdi.PacketStream.readValue(PacketStream.java:504)
    at com.sun.tools.jdi.JDWP$StackFrame$GetValues.<init>(JDWP.java:7127)
    at com.sun.tools.jdi.JDWP$StackFrame$GetValues.waitForReply(JDWP.java:7107)
    at com.sun.tools.jdi.StackFrameImpl.getValues(StackFrameImpl.java:233)
    at com.sun.tools.jdi.StackFrameImpl.getValue(StackFrameImpl.java:201)
    at org.jf.smalidea.debugging.SmaliCodeFragmentFactory.evaluateRegister(SmaliCodeFragmentFactory.java:316)
    at org.jf.smalidea.debugging.value.LazyValue.getNullableValue(LazyValue.java:116)
    at org.jf.smalidea.debugging.value.LazyValue.equals(LazyValue.java:157)
    at com.intellij.debugger.ui.impl.watch.ValueDescriptorImpl.setContext(ValueDescriptorImpl.java:210)
    at com.intellij.debugger.engine.JavaDebuggerEvaluator$1.threadAction(JavaDebuggerEvaluator.java:95)
    at com.intellij.debugger.engine.events.DebuggerContextCommandImpl.contextAction(DebuggerContextCommandImpl.java:83)
    at com.intellij.debugger.engine.events.SuspendContextCommandImpl.action(SuspendContextCommandImpl.java:61)
    at com.intellij.debugger.engine.events.DebuggerCommandImpl.run(DebuggerCommandImpl.java:45)
    at com.intellij.debugger.engine.DebuggerManagerThreadImpl.processEvent(DebuggerManagerThreadImpl.java:153)
    at com.intellij.debugger.engine.DebuggerManagerThreadImpl.processEvent(DebuggerManagerThreadImpl.java:40)
    at com.intellij.debugger.impl.InvokeThread.run(InvokeThread.java:153)
    at com.intellij.debugger.impl.InvokeThread.access$100(InvokeThread.java:31)
    at com.intellij.debugger.impl.InvokeThread$WorkerThreadRequest.run(InvokeThread.java:60)
    at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:369)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)

```

```
4
```

**Comment by JesusFreke** [comment]
This is likely fixed by https://github.com/JesusFreke/smali/commit/0e773cbe9be9824e586b3ac4c9f36f3d0ec85ecc
