### ISSUE TITLE
NPE in SmaliCodeFragmentFactory.evaluateRegister

### ISSUE THREAD

**Issue by SmalideaIssueReporter** [SmalideaIssueReporter/smalidea-issues#9]
protocol.version: 1
os.name: Windows 10
java.version: 1.8.0_77
java.vm.vendor: Oracle Corporation
app.name: IDEA
app.name.full: IntelliJ IDEA
app.name.version: IntelliJ IDEA
app.eap: false
app.internal: false
app.build: IC-145.972
app.version.major: 2016
app.version.minor: 1.2
app.build.date: 1463205600000
app.build.date.release: 1463205600000
app.compilation.timestamp: null
update.channel.status: release
update.ignored.builds: 
plugin.name: Smalidea
plugin.version: 0.03
last.action: Debug
previous.exception: null
assignee.id: null

```
java.lang.NullPointerException
    at com.sun.tools.jdi.LocalVariableImpl.isVisible(LocalVariableImpl.java:135)
    at com.sun.tools.jdi.StackFrameImpl.getValues(StackFrameImpl.java:214)
    at com.sun.tools.jdi.StackFrameImpl.getValue(StackFrameImpl.java:201)
    at org.jf.smalidea.debugging.SmaliCodeFragmentFactory.evaluateRegister(SmaliCodeFragmentFactory.java:316)
    at org.jf.smalidea.debugging.value.LazyValue.getNullableValue(LazyValue.java:116)
    at org.jf.smalidea.debugging.value.LazyValue.hashCode(LazyValue.java:165)
    at java.util.HashMap.hash(HashMap.java:338)
    at java.util.HashMap.put(HashMap.java:611)
    at java.util.HashSet.add(HashSet.java:219)
    at com.intellij.debugger.engine.SuspendContextImpl.keep(SuspendContextImpl.java:203)
    at com.intellij.debugger.impl.DebuggerUtilsEx.keep(DebuggerUtilsEx.java:455)
    at com.intellij.debugger.ui.impl.watch.EvaluationDescriptor.calcValue(EvaluationDescriptor.java:127)
    at com.intellij.debugger.ui.impl.watch.ValueDescriptorImpl.setContext(ValueDescriptorImpl.java:199)
    at com.intellij.debugger.engine.JavaDebuggerEvaluator$1.threadAction(JavaDebuggerEvaluator.java:95)
    at com.intellij.debugger.engine.events.DebuggerContextCommandImpl.contextAction(DebuggerContextCommandImpl.java:83)
    at com.intellij.debugger.engine.events.SuspendContextCommandImpl.action(SuspendContextCommandImpl.java:61)
    at com.intellij.debugger.engine.events.DebuggerCommandImpl.run(DebuggerCommandImpl.java:45)
    at com.intellij.debugger.engine.DebuggerManagerThreadImpl.processEvent(DebuggerManagerThreadImpl.java:153)
    at com.intellij.debugger.engine.DebuggerManagerThreadImpl.processEvent(DebuggerManagerThreadImpl.java:40)
    at com.intellij.debugger.impl.InvokeThread.run(InvokeThread.java:153)
    at com.intellij.debugger.impl.InvokeThread.access$100(InvokeThread.java:31)
    at com.intellij.debugger.impl.InvokeThread$WorkerThreadRequest.run(InvokeThread.java:60)
    at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:369)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)

```

```
null
```

**Comment by JesusFreke** [comment]
Tentatively fixed by https://github.com/JesusFreke/smali/commit/8f7d1a897df243a8fafcaec6c193477e73f54ef3
